### ISSUE TITLE
PSSM generation error on demo

### ISSUE THREAD

**Issue by m-kilian** [BioinfoMachineLearning/CDPred#8]
Hello, I am interested to run CDPred on some targets for inter-chain contact predictions.
I followed the instructions in your README.md on a Linux Mint 21.1 system, but am unable to reproduce your examples due to an error during the PSSM generation step in `python lib/Model_predict.py -n T1084A_T1084B -p ./example/T1084A_T1084B.pdb -a ./example/T1084A_T1084B.a3m -m homodimer -o ./output/T1084A_T1084B/`.

During setup, I downloaded the new Uniref90 archive as described in #7 from Zenodo directly, and unpacked it into the CDPred folder. 
I verified just like in #7 that PSI-BLAST is working with the database by executing `./bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d ./uniref90_01_2020/uniref90 -i ./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.fasta -Q ./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.pssm >% T1084A_T1084B.psiblast.output`, using the expected output instead of the input sequence from the demo. Here, I got an error-free run reproducing the expected output exactly.
Therefore, PSSM generation appears to fail if the example input A3M alignment is used by the Model_predict.py script, and thus PSI-BLAST cannot continue. Do you have any idea how to fix this problem?

Here is the complete log of trying to run the homodimer example with the feature generate errors produced: [log.txt](https://github.com/BioinfoMachineLearning/CDPred/files/11788720/log.txt)

For sake of completeness, I have also attached a list of packages in the CDPred Python 3.6.8 environment (installed according to your installation guide): [environment.txt](https://github.com/BioinfoMachineLearning/CDPred/files/11788639/environment.txt)

Thanks for your help.

**Comment by ZhiYeG** [comment]
I will work on this problem, some error in the Uniref90 database mainly causes this. I will download and go through the whole process, however, due to the limitation of internet speed, this may take some time. I'll let you know when I am done.

**Comment by ZhiYeG** [comment]
> 

Have you checked the output folder? Is the pssm file generated successfully or not? Is there any final output file exists in the output file? I try the whole process on my side. I did get the error, but I also got the pssm file and final results. This might be the wrong error message from some old code. I will keep looking into that. Let me know your thought.

**Comment by ZhiYeG** [comment]
There in one minor bug in feature generate scripts. I already fixed it. Feel free to pull the new code and try it out

**Comment by m-kilian** [comment]
I pulled your new code and still get an error, so this issue is not closed. 

> > 
> 
> Is the pssm file generated successfully or not? Is there any final output file exists in the output file? I try the whole process on my side. I did get the error, but I also got the pssm file and final results.

While the code did generate a folder for the pssm data in .output/T1084A_T1084/feature/, it only contains the fasta query for PSI-BLAST and no PSSM file. It also does not work if I copy the expected output of the PSSM from the `example/expection_output/...` to the output folder, I get an error before that.

**Comment by m-kilian** [comment]
Here's an error log when I use your last code update on the homodimer demo: [log_update.txt](https://github.com/BioinfoMachineLearning/CDPred/files/11815006/log_update.txt)

**Comment by ZhiYeG** [comment]
> txt
This is cause by the CCMpred binary file may not compatible with your current environment. Could you run the CCMPred alone and see what can we get?

**Comment by ZhiYeG** [comment]
> I pulled your new code and still get an error, so this issue is not closed.
> 
> > > 
> > 
> > 
> > Is the pssm file generated successfully or not? Is there any final output file exists in the output file? I try the whole process on my side. I did get the error, but I also got the pssm file and final results.
> 
> While the code did generate a folder for the pssm data in .output/T1084A_T1084/feature/, it only contains the fasta query for PSI-BLAST and no PSSM file. It also does not work if I copy the expected output of the PSSM from the `example/expection_output/...` to the output folder, I get an error before that.

Have you verified the database location in the constants.py file?

**Comment by m-kilian** [comment]
> Have you verified the database location in the constants.py file?

Yes, in my first comment I verified that the blastpgp command that is ran in the perl script works if I use the expected output PSSM for the demo targets. So the database is set up correctly and the path to it works.

> This is cause by the CCMpred binary file may not compatible with your current environment. Could you run the CCMPred alone and see what can we get?

I think that's the problem. I checked running ccmpred directly and got
`./bin/ccmpred: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory`.
I assume the version of ccmpred provided with your code was compiled with an old version of libncurses I don't have installed on my machine? I only have libncurses6 and libncursesw6 on my Linux system (a Linux Mint 21.1 system). I have double-checked that this same error also happens on an Ubuntu 20.04 system with a similar setup. 

Probably, the requirements provided with your code are not complete then as you need additional libraries to execute the CCMpred binary in your bin folder.

**Comment by ZhiYeG** [comment]
I test just fine both on the local Ubuntu20.04 system and Ubuntu18.04 about the CCMpred binary file.  So for this problem, you should add the missing shared libraries file to your system lib folder. As for the PSSM feature error, I would suggest you re-download the database and make sure the database is complete, it contains 184 files and the total is 113.0GB

**Comment by m-kilian** [comment]
I have contacted my sysadmins to install the missing shared libraries - no root access on this workstation here, sadly. I will keep you posted if that has resolved the issues with executing ccmpred and the downstream code.

> I would suggest you re-download the database and make sure the database is complete, it contains 184 files and the total is 113.0GB

Just to be sure, I redownloaded from zenodo and after unzipping according to your installation instructions I have 184 files with a total of 105GB. Blastpgp still works with the redownloaded version as well as previously.

**Comment by m-kilian** [comment]
ccmpred works now after the required shared libraries were installed. You should probably add to your README then that ccmpred specifically requires libncurses5 to execute the provided binary - or you compile it yourself from source.
However, I still get the feature generate error during PSSM generation, so I am a little lost as to what is happening in the code that it fails.

**Comment by ZhiYeG** [comment]
> 

After you donwload the Uniref90 from zenodo,  and do one setp xz -d -T 4 uniref90_01_2020.tar.xz, then what size is the uniref90_01_2020.tar? Is this file 113GB? If not, the database is not complete. Which way do you try to download the unire90, wget, or something else?

**Comment by m-kilian** [comment]
I downloaded again today from the latest record in https://zenodo.org/record/7650566 (the database generated in #7) and unzipped according to your readme. Here are the file sizes of each file:
```
$ wget https://zenodo.org/record/7650566/files/uniref90_01_2020.tar.xz
> File size uniref90_01_2020.tar.xz: 38GB
$ xz -d -T 4 uniref90_01_2020.tar.xz
> File size uniref90_01_2020.tar: 106GB
$ tar -xvf uniref90_01_2020.tar
> File size /uniref90_01_2020/ folder: 106GB
```
Unsure where the few missing gigabytes have been lost then.
I also (again) verified that the re-downloaded database gives me an error-free run with the expected output PSSM during PSI-BLAST on the homodimer target with 
`./bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d ./uniref90_01_2020/uniref90 -i ./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.fasta -Q ./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.pssm > T1084A_T1084B.psiblast.output`, so the database seems to be fine either way.

**Comment by ZhiYeG** [comment]
You can generate pssm file now, so can you run the whole process now? Please let me know if you encounter any more errors.

**Comment by m-kilian** [comment]
During verification of the re-downloaded database I used the expected output PSSM provided with the demo with PSI-BLAST to check if the database works. PSSM generation from scratch when running the entire homodimer demo still fails as before.
Here's the error log, unchanged from the prior runs I tried:

```
(cdpred) bq_mkilian@mpi-pc-ib26:/data/cdpred/CDPred$ python lib/Model_predict.py -n T1084A_T1084B -p ./example/T1084A_T1084B.pdb -a ./example/T1084A_T1084B.a3m -m homodimer -o ./output/T1084A_T1084B/
Using TensorFlow backend.
### Find gloabl path : /data/cdpred/CDPred
### Find model path : /data/cdpred/CDPred/model/homo/
2023-06-28 19:56:32.500757: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
71 71
### Generate features
(71, 71, 144)
save file to /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.npy
feature generate error T1084A_T1084B
perl /data/cdpred/CDPred/bin/genpssm.pl /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta /data/cdpred/CDPred/output/T1084A_T1084B/feature/ /data/cdpred/CDPred/uniref90_01_2020/uniref90
b'/data/cdpred/CDPred/bin\nInput: /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta\nL    : 71\nSeq  : AHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH\n\n\n\nGenerating PSSM..\n[[Executing: mkdir -p /data/cdpred/CDPred/output/T1084A_T1084B/feature//pssm]]\n[[Executing: cp ../T1084A_T1084B.fasta ./]]\nRunning PSI-Blast with /data/cdpred/CDPred/uniref90_01_2020/uniref90...\n[[Executing: /data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]]\nsh: 1: Syntax error: Bad fd number\nERROR!! Could not execute [/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]! \nError message: [No such file or directory] at /data/cdpred/CDPred/bin/genpssm.pl line 175.\n\tmain::system_cmd("/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.0"...) called at /data/cdpred/CDPred/bin/genpssm.pl line 120\n\tmain::generate_pssm("T1084A_T1084B.fasta", "T1084A_T1084B.pssm", "T1084A_T1084B.psiblast.output") called at /data/cdpred/CDPred/bin/genpssm.pl line 75\n'
None
Traceback (most recent call last):
  File "lib/Model_predict.py", line 208, in <module>
    selected_list_2D = get2d_feature_by_list(name, accept_list, a3m_file, rowatt_file = rowatt_file, ccmpred_file = ccmpred_file, pssm_file = pssm_file, pred_dist_file_cb=pred_dist_file)
  File "/data/cdpred/CDPred/lib/generate_feature.py", line 271, in get2d_feature_by_list
    feature = np.concatenate([feature, computepssm_fromfile(pssm_file)], axis = -1)
  File "/data/cdpred/CDPred/lib/generate_feature.py", line 87, in computepssm_fromfile
    pssm_rawdata = np.loadtxt(pssmfile)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/npyio.py", line 955, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B_pssm.txt not found.

```

**Comment by ZhiYeG** [comment]
I'm a little bit confused, have you ever successfully generated the pssm.txt file or .pssm file? Since you said you can get the expected output when you run PSI-BLAST only that means you have generated the T1084A_T1084B.pssm correctly, right? If not, could you put content in file T1084A_T1084B.psiblast.output here, also along with error.log file if it's not empty? Alternatively, you can just simply run ./lib/generate_feature.py to test that all features can be generated reasonably.

**Comment by m-kilian** [comment]
Sorry for the confusion, let me try to be a little clearer.

> have you ever successfully generated the pssm.txt file or .pssm file?

No, not when I try to execute the demo commands - I get the PSSM feature generate error shown in my last comment in generate_feature.py.

> Since you said you can get the expected output when you run PSI-BLAST only that means you have generated the T1084A_T1084B.pssm correctly, right?

No. For running the PSI-BLAST test, I used the T1084A_T1084B.pssm from the expected output of the demo to simply verify whether there is an issue with the uniref90 database or not. There I don't get any errors, so I believe the database is fine.
When running the demo the pipeline fails during the PSI-BLAST step because no PSSM was generated due to a feature generate error.

**Comment by ZhiYeG** [comment]
Could you put content in file T1084A_T1084B.psiblast.output here？

**Comment by m-kilian** [comment]
This is the output of running PSI-BLAST only on the homodimer demo on my machine with the expected output PSSM: [T1084A_T1084B.psiblast.output](https://github.com/BioinfoMachineLearning/CDPred/files/11909867/T1084A_T1084B.psiblast.output.txt)
Compare to the [expected output](https://github.com/BioinfoMachineLearning/CDPred/blob/main/example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.psiblast.output) in `./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.psiblast.output`.

**Comment by ZhiYeG** [comment]
> 
Dose this output folder contain T1084A_T1084B.pssm file? It seems this output file is the right one.

**Comment by m-kilian** [comment]
No it does not. 

I don't know how to make this much clearer, but because you were concerned about the integrity of the database and because of the procedure described in #7, I simply verified whether PSI-BLAST would work if the PSSM was generated correctly (using the EXPECTED PSSM provided with your repository in `/example/expection_output/T1084A_T1084B/feature/pssm/` as the input to call PSI-BLAST directly, the command I used is shown in an earlier comment). 
Because the output from that test on one part of the pipeline is correct, I believe the feature generate error if I run the entire pipeline is not because the database is faulty.

So: I tried again to run the entire homodimer demo with the command you provide in your README:
`python lib/Model_predict.py -n T1084A_T1084B -p ./example/T1084A_T1084B.pdb -a ./example/T1084A_T1084B.a3m -m homodimer -o ./output/T1084A_T1084B/`
The error which I got, and why I opened this issue to begin with, is still the same after redownloading the database, verifying that the database works with PSI-BLAST, and getting your latest code updates:
```
(cdpred) bq_mkilian@mpi-pc-ib26:/data/cdpred/CDPred$ python lib/Model_predict.py -n T1084A_T1084B -p ./example/T1084A_T1084B.pdb -a ./example/T1084A_T1084B.a3m -m homodimer -o ./output/T1084A_T1084B/
Using TensorFlow backend.
### Find gloabl path : /data/cdpred/CDPred
### Find model path : /data/cdpred/CDPred/model/homo/
2023-06-28 19:56:32.500757: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
71 71
### Generate features
(71, 71, 144)
save file to /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.npy
**feature generate error T1084A_T1084B
perl /data/cdpred/CDPred/bin/genpssm.pl /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta /data/cdpred/CDPred/output/T1084A_T1084B/feature/ /data/cdpred/CDPred/uniref90_01_2020/uniref90
b'/data/cdpred/CDPred/bin\nInput: /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta\nL    : 71\nSeq  : AHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH\n\n\n\nGenerating PSSM..\n[[Executing: mkdir -p /data/cdpred/CDPred/output/T1084A_T1084B/feature//pssm]]\n[[Executing: cp ../T1084A_T1084B.fasta ./]]\nRunning PSI-Blast with /data/cdpred/CDPred/uniref90_01_2020/uniref90...\n[[Executing: /data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]]\nsh: 1: Syntax error: Bad fd number\nERROR!! Could not execute [/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]! \nError message: [No such file or directory] at /data/cdpred/CDPred/bin/genpssm.pl line 175.\n\tmain::system_cmd("/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.0"...) called at /data/cdpred/CDPred/bin/genpssm.pl line 120\n\tmain::generate_pssm("T1084A_T1084B.fasta", "T1084A_T1084B.pssm", "T1084A_T1084B.psiblast.output") called at /data/cdpred/CDPred/bin/genpssm.pl line 75\n'**
None
Traceback (most recent call last):
  File "lib/Model_predict.py", line 208, in <module>
    selected_list_2D = get2d_feature_by_list(name, accept_list, a3m_file, rowatt_file = rowatt_file, ccmpred_file = ccmpred_file, pssm_file = pssm_file, pred_dist_file_cb=pred_dist_file)
  File "/data/cdpred/CDPred/lib/generate_feature.py", line 271, in get2d_feature_by_list
    feature = np.concatenate([feature, computepssm_fromfile(pssm_file)], axis = -1)
  File "/data/cdpred/CDPred/lib/generate_feature.py", line 87, in computepssm_fromfile
    pssm_rawdata = np.loadtxt(pssmfile)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/npyio.py", line 955, in loadtxt
    fh = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/home/bq_mkilian/.conda/envs/cdpred/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 624, in open
    raise IOError("%s not found." % path)
OSError: /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B_pssm.txt not found.
```

**Comment by ZhiYeG** [comment]
>  I simply verified whether PSI-BLAST would work if the PSSM was generated correctly (using the EXPECTED PSSM provided with your repository in /example/expection_output/T1084A_T1084B/feature/pssm/ as the input to call PSI-BLAST directly, the command I used is shown in an earlier comment)

This is the one that got me really really confused. We use PSI-BLAST for pssm generate, the pssm file should be the output. However, you use it as one input for validation.  You can't get anything from this. If you just want to simply run PSI-BLAST for pssm generate only use command `./bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d ./database/uniref90_01_2020/uniref90 -i ./example/expection_output/T1084A_T1084B/feature/pssm/T1084A_T1084B.fasta -Q T1084A_T1084B.pssm`. Then you can check what you can get from the terminal and if there exists a T1084A_T1084B.pssm file after running.

**Comment by m-kilian** [comment]
Ok that makes sense, sorry for the confusion - it wasn't clear to me from your code and what was described in issue #7 that the PSSM is the output from the PSI-BLAST... if I run PSI-BLAST in isolation as you describe it now, I do get a PSSM file on the homodimer demo:
[T1084A_T1084B.pssm](https://github.com/BioinfoMachineLearning/CDPred/files/11928921/T1084A_T1084B.pssm.txt)
If I then paste this into the `./output/feature/pssm/` folder and call `./lib/model_predict.py` on the homodimer demo there's no feature generate error anymore, and the correct feature maps are generated.

That still doesn't explain why the pipeline in `./lib/model_predict.py` fails if I don't precompute the PSSM, but I guess I can then use PSI-BLAST to make the PSSMs for my own targets.

**Comment by ZhiYeG** [comment]
Could you run ./lib/generate_feature.py to test if any error exists while generating the pssm feature? If PSI-BLAST worked for you, there may be some error in the genpssm.pl scripts.

**Comment by m-kilian** [comment]
I did some code digging and I managed to fix the feature generate errors by adjusting the genpssm.pl script.
There was an issue with writing the PSI-BLAST output to the disk with the used syntax on my shell:
```
**feature generate error T1084A_T1084B
perl /data/cdpred/CDPred/bin/genpssm.pl /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta /data/cdpred/CDPred/output/T1084A_T1084B/feature/ /data/cdpred/CDPred/uniref90_01_2020/uniref90
b'/data/cdpred/CDPred/bin\nInput: /data/cdpred/CDPred/output/T1084A_T1084B/feature//T1084A_T1084B.fasta\nL    : 71\nSeq  : AHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH\n\n\n\nGenerating PSSM..\n[[Executing: mkdir -p /data/cdpred/CDPred/output/T1084A_T1084B/feature//pssm]]\n[[Executing: cp ../T1084A_T1084B.fasta ./]]\nRunning PSI-Blast with /data/cdpred/CDPred/uniref90_01_2020/uniref90...\n[[Executing: /data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]]\nsh: 1: Syntax error: Bad fd number\nERROR!! Could not execute [/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output]! \nError message: [No such file or directory] at /data/cdpred/CDPred/bin/genpssm.pl line 175.\n\tmain::system_cmd("/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.0"...) called at /data/cdpred/CDPred/bin/genpssm.pl line 120\n\tmain::generate_pssm("T1084A_T1084B.fasta", "T1084A_T1084B.pssm", "T1084A_T1084B.psiblast.output") called at /data/cdpred/CDPred/bin/genpssm.pl line 75\n'**
```

The "bad fd number" error in this arises from improper file descriptor syntax in the `/data/cdpred/CDPred/bin/blast-2.2.26/bin/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d /data/cdpred/CDPred/uniref90_01_2020/uniref90 -i T1084A_T1084B.fasta -Q T1084A_T1084B.pssm >& T1084A_T1084B.psiblast.output` command called by genpssm.pl to write into the psiblast.output file. I verified that my Linux system uses a shell that doesn't use the `>& `syntax. It seems to be a classic issue when calling shell commands from within scripts, [here's an example issue I found](https://unix.stackexchange.com/questions/407798/syntax-error-bad-fd-number). Then the PSSM file isn't generated and the downstream pipeline that requires the PSSM fails.
Issue #7 also had this error in the logs.

I simply fixed the error then by exchanging `>&` to `>` in the genpssm.pl script wherever applicable, e.g. for the generate_pssm function:
```
sub generate_pssm{
	my $FASTA = shift;
	my $PSSM = shift;
	my $REPORT = shift;
	print "Running PSI-Blast with $unirefdb...\n";
	#system_cmd($db_tool_dir.BLASTPATH. "/psiblast -query ".$FASTA." -evalue .001 -inclusion_ethresh .002 -db $unirefdb -num_iterations 3 -outfmt 0 -out $REPORT -seg yes -out_ascii_pssm $PSSM");
	system_cmd($workdir.BLASTPATH. "/blastpgp -a 8 -e 0.001 -j 3 -h 0.002 -d $unirefdb -i $FASTA -Q $PSSM > $REPORT");
}
```

I could then successfully run both the homo- and heteromer demo without any errors. I assume this may be a general issue when running your current code on other Linux systems, so consider adjusting the `>&` to `>` in genpssm.pl script in your repo.
Thanks for your help and time (and sorry for the confusion), hopefully I can move forward with my project using your tool now!
